couple_factor:
  value_type: number
  value: 2
  description: The number threasholds are multiplied by if the user is part of a couple

lower_savings_threshold:
  value_type: decimal
  value: 14250
  description: The amount of savings above which a users is likely to have to pay for SOME services

upper_savings_threshold:
  value_type: decimal
  value: 23250
  description: The amount of savings above which a users is likely to have to pay for ALL services

cope_index_threshold:
  value_type: number
  value: 20
  description: The sum of cope_index values at which a customer action occurs

community_care_assessment_url:
  value_type: text
  value: http://www.warwickshire.gov.uk/yoursocialcareneed
  description: Destination users sent to if they select a link to information on a getting a community care assessment