
defaults: &defaults
  adapter: mysql2
  username: rails_app
  password: GTYHdse23B
  host: localhost

development:
  <<: *defaults
  database: self_assessment_development

test:
  <<: *defaults
  database: self_assessment_test
  
production:
  <<: *defaults
  database: self_assessment